apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: ftps
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.201
  selector:
    app: ftps
  ports:
  - name: ftp-data
    port: 20
  - name: ftp-connection
    port: 21
  - name: pftp-data-0
    port: 30000